### PR TITLE
Remove a Bono node from cluster

### PR DESCRIPTION
**Pull request by junaid-ali**
Updating stop.sh script as per the instructions available at:
https://clearwater.readthedocs.io/en/latest/Clearwater_Elastic_Scaling.html#if-you-did-a-manual-install

### CODE REVIEW

**Comment by junaid-ali** [comment]
The scripts for other nodes need update as well but I haven't tested them yet.

**Comment by boucherv** [comment]
Hi @junaid-ali,

Thanks for your Pull Request!

I'm not sure this is needed because in the documentation your updated line is only for the ETCD master node and not all the nodes or all bono nodes):

> If the node you are turning down is a Vellum node, or another node configured to act as an etcd master, also do the following

If you try those lines on other nodes (sprout etc) and if it work maybe we can update all nodes stop script but we must to be sure before!

Valentin

**Comment by junaid-ali** [comment]
The existing scrpt wasn't working for me because of missing `-g` argument in this command: `sudo monit unmonitor clearwater_config_manager` in stop.sh

Though adding `-g` enabled the script to run successfully but `clearwater-cluster-manager config-manager queue-manager etcd` are also running on bono node. I don't know much about etcd but isn't an etcd cluster masterless?

**Comment by junaid-ali** [comment]
Etcd has a leader node:
https://speakerdeck.com/benbjohnson/raft-the-understandable-distributed-consensus-protocol

**Comment by junaid-ali** [comment]
Agreed, it would need more testing.

**Pull request closed without merging**
